---





- name: Configuration for Production
  hosts: all
  become: yes
  vars:
      user_name: "vagrant"
      group_name: "vagrant"

  roles:
    - common
    - python
    - {role: gunicorn, autostart: true, enabled: true}
    - {role: nginx, enabled: true}